@host= http://localhost:3000

GET {{host}}/api/blog/blogvisitor http/1.1
###

POST  http://localhost:3000/api/blog/blogvisitor HTTP/1.1
Content-Type: application/json

{
"blog":"ccs3", "user":"khalid", "ip":"89.207.132.170","counter":3655
}

###

PUT    http://localhost:3000/api/blog/blogvisitor HTTP/1.1
Content-Type: application/json


###
PUT {{host}}/api/blog/blogvisitor/enai http/1.1
