import "../../styles/globals.css";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/header/Navbar";
import { Locale, i18n } from "@/i18n.config";
import dynamic from "next/dynamic";
const Providers = dynamic(() => import("@/Providers/Provider"));
import { Analytics } from '@vercel/analytics/react';

import {roboto,lateef,cairo,tajawal} from "@/lib/fonts"

// export const dynamic ='force-dynamic'
// export const revalidate = 0

export const metadata = {
  title: "EazyCode",
  description: "Generated by create next app",
};

export async function generateStaticParams() {

  // console.log("from array: ", i18n.locales);
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({ children, params }) {

  return (
    <html lang={params.lang} dir={params.lang === "ar" ? "rtl" : "ltr"}>
        <body
          className={`${cairo.variable} ${lateef.variable}  ${tajawal.variable}  bg-slate-400 text-white dark:bg-gradient-to-t from-slate-900 to-blue-900`}
          >
          <Providers>
          <Container>
            <Navbar lang={params.lang} />
            <section className="flex flex-col  justify-start items-start h-[calc(100vh_-_170px)] ">
              {children}
              <Analytics />
            </section>
            <Footer />
          </Container>
      </Providers>
        </body>
    </html>
  );
}

const Container = ({ children }) => {
  return (
    <>
      <div className="container relative min-w-full px-6 py-4 ">
        {children}{" "}
      </div>
    </>
  );
};
