import "../../styles/globals.css";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/header/Navbar";
import { Locale, i18n } from "@/i18n.config";
import dynamic from "next/dynamic";
const Providers = dynamic(() => import("@/Providers/Provider"));
import { Roboto } from "next/font/google";
import { Lateef } from "next/font/google";
import { Cairo } from "next/font/google";
import { Tajawal } from "next/font/google";
import { Analytics } from '@vercel/analytics/react';
// export const runtime = 'edge'

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
  fallback: ["system-ui", "arial"],
});
const lateef = Lateef({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["arabic"],
  display: "swap",
  variable: "--font-lateef",
  fallback: ["system-ui", "arial"],
});
const cairo = Cairo({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["arabic"],
  display: 'swap', adjustFontFallback: false,
  variable: "--font-cairo",
  fallback: ["system-ui", "arial"],
});
const tajawal = Tajawal({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["arabic"],
  display: 'swap', adjustFontFallback: false,
  variable: "--font-tajawal",
  fallback: ["system-ui", "arial"],
});
// export const dynamic ='force-dynamic'
export const revalidate = 0

export const metadata = {
  title: "EazyCode",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  // console.log("from array: ", i18n.locales);
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({ children, params }) {

  return (
    <html lang={params.lang} dir={params.lang === "ar" ? "rtl" : "ltr"}>
        <body
          className={`${cairo.variable} ${lateef.variable}  ${tajawal.variable}  bg-slate-400 text-white dark:bg-gradient-to-t from-slate-900 to-blue-900`}
          >
          <Providers>
          <Container>
            <Navbar lang={params.lang} />
            <section className="flex flex-col  justify-start items-start h-[calc(100vh_-_170px)] ">
              {children}
              <Analytics />
            </section>
            <Footer />
          </Container>
      </Providers>
        </body>
    </html>
  );
}

const Container = ({ children }) => {
  return (
    <>
      <div className="container relative min-w-full px-6 py-4 ">
        {children}{" "}
      </div>
    </>
  );
};
