import "../../styles/globals.css";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/header/Navbar";
import { Locale, i18n } from "@/i18n.config";
import dynamic from "next/dynamic";
const Providers = dynamic(() => import("@/Providers/Provider"));
import { Analytics } from "@vercel/analytics/react";
import { lateef, cairo, tajawal } from "@/lib/fonts";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "EazyCode",
  description: "Generated by create next app",
};

// export async function generateStaticParams() {
//   return i18n.locales.map(async (locale) => await { lang: locale });
// }

export async function generateStaticParams() {
  return [{ lang: "en" }, { lang: "ar" }];
}

export default function RootLayout({ children, params }) {
  return (
    <html
      lang={params.lang}
      dir={params.lang === "ar" ? "rtl" : "ltr"}
      style={{ colorScheme: "light" }}
    >
      <body
        className={`${cairo.variable} ${lateef.variable}  ${tajawal.variable}  p-4 `}
      >
        <Providers>
          {/* <Container> */}
          <Navbar lang={params.lang} />
          <section
            id="childrenxx"
            className="flex flex-col    justify-start items-start h-[calc(100vh_-_170px)] "
          >
            {children}
            <Toaster />
            <Analytics />
          </section>
          <Footer />
          {/* </Container> */}
        </Providers>
      </body>
    </html>
  );
}

const Container = ({ children }) => {
  return (
    <>
      <div
        id="container"
        className="container relative min-w-full px-6 py-4 border-4bg-[#f5f5f5] text-black dark:bg-gradient-to-t from-slate-900 to-blue-900 "
      >
        {children}
      </div>
    </>
  );
};
