import DashBoardMenu from '@/pagecomponent/dashboard/DashBoardMenu';
import PageContainer from '@/components/shared/pagecontainer/PageContainer';
export const metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app',
};

export default function DashboardLayout({ children, params }) {
    return (
        <>
            <PageContainer>
                <section className='relative flex h-full w-full rounded-sm'>
                    <aside className='absolute -top-3 left-1  z-10 h-fit'>
                        <DashBoardMenu lang={params.lang} />
                    </aside>
                    <main className='w-full'>{children}</main>
                </section>
            </PageContainer>
            {/* </div> */}
        </>
    );
}
