import DashBoardMenu from "@/components/pagecomponent/dashboard/DashBoardMenu";
import PageContainer from "@/components/shared/pagecontainer/PageContainer";
export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children, left, params }) {
  return (
    <>
      <PageContainer>
        <section className="flex w-full h-full p-2 border rounded-sm border-gray-300/30">
          <aside>
            {/* {left} */}

            <DashBoardMenu />
          </aside>
          <main className="flex-1 overflow-auto">{children}</main>
        </section>
      </PageContainer>
      {/* </div> */}
    </>
  );
}
