import dynamic from "next/dynamic";
import DashBoardMenu from "@/components/pagecomponent/dashboard/DashBoardMenu";
// import Dashboard from "@/app/dashboard";
export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children, params }) {
  return (
    <>
      {/* <div className="flex justify-between w-full"> */}
      <section className="flex w-full h-full">
        <aside>
          <DashBoardMenu /> {/* <Dashboard lang={params.lang} /> */}
        </aside>
        <main className="flex-1 overflow-auto">{children}</main>
      </section>
      {/* </div> */}
    </>
  );
}
